# Dataset Terapi

### Load Data

In [63]:
#importing library 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from collections import Counter
from sklearn.model_selection import train_test_split

In [64]:
#load csv
df = pd.read_csv('https://raw.githubusercontent.com/Bryant35/Data_Mining/main/ALP/Bryant%20Anthony%20Thauwrisan_ALP_0706022010008/Dataset_Terapi_Kelenjar_Getah_Bening.csv')
df


gender  age   Time  Number_of_Warts  Type  Area  induration_diameter  \
0        1   15  11.00              6.0   1.0    30                 25.0   
1        1   27  11.75              NaN   1.0   208                  6.0   
2        1   32  12.00              9.0   1.0    43                 50.0   
3        1   33   1.75              7.0   2.0   379                  7.0   
4        1   34   5.00              7.0   3.0    64                  7.0   
..     ...  ...    ...              ...   ...   ...                  ...   
85       2   51   4.00              1.0   1.0    65                  7.0   
86       2   51   6.00              6.0   NaN    80                  2.0   
87       2   52   2.25              5.0   1.0    63                  7.0   
88       2   53  10.00              1.0   2.0    30                 25.0   
89       2   53   7.25              6.0   NaN    81                  7.0   

    Result_of_Treatment  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
..                  ...  
85                    1  
86                    1  
87                    1  
88                    1  
89                    1  

[90 rows x 8 columns]

### EDA

#### Data Check

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   gender               90 non-null     int64  
 1   age                  90 non-null     int64  
 2   Time                 87 non-null     float64
 3   Number_of_Warts      89 non-null     float64
 4   Type                 85 non-null     float64
 5   Area                 90 non-null     int64  
 6   induration_diameter  88 non-null     float64
 7   Result_of_Treatment  90 non-null     int64  
dtypes: float64(4), int64(4)
memory usage: 5.8 KB


In [66]:
df.isnull().sum()

gender                 0
age                    0
Time                   3
Number_of_Warts        1
Type                   5
Area                   0
induration_diameter    2
Result_of_Treatment    0
dtype: int64

### Desc

1. Dataset ini sangat sedikit karena < 100 baris jadi diharapkan
   TIDAK MENGHAPUS baris data.
2. Target atribut dataset ini sangat imbalance jadi silakan menggunakan berbagai
   metode untuk menangani imbalance class
3. Untuk gender: 1 untuk male dan 2 untuk female
   Untuk results: 0 untuk tidak ada kemajuan dan 1 untuk ada kemajuan
4. Silakan membangun model Machine Learning dengan task baik 
   Classification, Regression, atau Clustering.
5. Silakan mengunggah notebook baik di e-learn maupun
   di Github (online text). Pastikan sudah urut code cell-nya dan harus
   sudah di- RUN ALL.

### Normalization #1

In [67]:
df = df.interpolate(method = 'pad')
df

gender  age   Time  Number_of_Warts  Type  Area  induration_diameter  \
0        1   15  11.00              6.0   1.0    30                 25.0   
1        1   27  11.75              6.0   1.0   208                  6.0   
2        1   32  12.00              9.0   1.0    43                 50.0   
3        1   33   1.75              7.0   2.0   379                  7.0   
4        1   34   5.00              7.0   3.0    64                  7.0   
..     ...  ...    ...              ...   ...   ...                  ...   
85       2   51   4.00              1.0   1.0    65                  7.0   
86       2   51   6.00              6.0   1.0    80                  2.0   
87       2   52   2.25              5.0   1.0    63                  7.0   
88       2   53  10.00              1.0   2.0    30                 25.0   
89       2   53   7.25              6.0   2.0    81                  7.0   

    Result_of_Treatment  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
..                  ...  
85                    1  
86                    1  
87                    1  
88                    1  
89                    1  

[90 rows x 8 columns]

In [68]:
df.isnull().sum()

gender                 0
age                    0
Time                   0
Number_of_Warts        0
Type                   0
Area                   0
induration_diameter    0
Result_of_Treatment    0
dtype: int64

In [69]:
df.duplicated().sum()

0

### Dealing with Imbalance Class

In [70]:
print(df['Result_of_Treatment'].value_counts())

1    71
0    19
Name: Result_of_Treatment, dtype: int64


In [71]:
#dependent variable and independent variable
X = df[['Result_of_Treatment']] == 0
y = df[['Result_of_Treatment']] == 1

In [72]:
#remapping
X = X.replace({True: 1, False: 0})
y = y.replace({True: 1, False: 0})

In [73]:
standard_sc = StandardScaler()
standard = pd.DataFrame(standard_sc.fit_transform(X),columns=X.columns)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [74]:
# SMOTE Oversampling
from imblearn.over_sampling import SMOTE
Count = Counter(y_train)
print(Count)
smt = SMOTE()
X_train_res, y_train_res = smt.fit_resample(X_train, y_train.values.ravel())
  
Counter2 = Counter(y_train_res)
print(Counter2)

Counter({'Result_of_Treatment': 1})
Counter({1: 48, 0: 48})


### Logistic Regression

In [75]:
from sklearn.linear_model import LogisticRegression

log = LogisticRegression(random_state = 0)
log.fit(X_train, y_train.values.ravel())

LogisticRegression(random_state=0)

In [76]:
y_pred = log.predict(X_test)
print(y_pred)

[1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [77]:
from sklearn.metrics import confusion_matrix, accuracy_score

confusion = confusion_matrix(y_pred, y_test)
print(confusion)
print("Accuracy Score :")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))

[[ 4  0]
 [ 0 23]]
Accuracy Score :
1.0
27


### KNN Classifier

In [78]:
from sklearn.neighbors import KNeighborsClassifier

log = KNeighborsClassifier(metric='euclidean')
log.fit(X_train, y_train)

c:\Users\ASUS\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(metric='euclidean')

In [79]:
y_pred = log.predict(X_test)
print(y_pred)

[1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [80]:
confusion = confusion_matrix(y_pred, y_test)
print(confusion)
print("Accuracy Score :")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))

[[ 4  0]
 [ 0 23]]
Accuracy Score :
1.0
27


### Naive Bayes

In [81]:
from sklearn.naive_bayes import GaussianNB

NB = GaussianNB()

In [82]:
NB.fit(X_train,y_train)
print(y_train)

    Result_of_Treatment
58                    1
82                    1
45                    1
57                    1
5                     0
..                  ...
88                    1
21                    1
1                     0
13                    0
0                     0

[63 rows x 1 columns]


c:\Users\ASUS\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [83]:
y_pred = NB.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix\n", cm)
print("Accuracy Score :")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))

Confusion Matrix
 [[ 4  0]
 [ 0 23]]
Accuracy Score :
1.0
27
