# Dataset Terapi

### Load Data

In [428]:
#importing library 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from collections import Counter
from sklearn.model_selection import train_test_split

In [429]:
#load csv
df = pd.read_csv('https://raw.githubusercontent.com/Bryant35/Data_Mining/main/ALP/Bryant%20Anthony%20Thauwrisan_ALP_0706022010008/Dataset_Terapi_Kelenjar_Getah_Bening.csv')
df


gender  age   Time  Number_of_Warts  Type  Area  induration_diameter  \
0        1   15  11.00              6.0   1.0    30                 25.0   
1        1   27  11.75              NaN   1.0   208                  6.0   
2        1   32  12.00              9.0   1.0    43                 50.0   
3        1   33   1.75              7.0   2.0   379                  7.0   
4        1   34   5.00              7.0   3.0    64                  7.0   
..     ...  ...    ...              ...   ...   ...                  ...   
85       2   51   4.00              1.0   1.0    65                  7.0   
86       2   51   6.00              6.0   NaN    80                  2.0   
87       2   52   2.25              5.0   1.0    63                  7.0   
88       2   53  10.00              1.0   2.0    30                 25.0   
89       2   53   7.25              6.0   NaN    81                  7.0   

    Result_of_Treatment  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
..                  ...  
85                    1  
86                    1  
87                    1  
88                    1  
89                    1  

[90 rows x 8 columns]

### EDA

#### Data Check

In [430]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   gender               90 non-null     int64  
 1   age                  90 non-null     int64  
 2   Time                 87 non-null     float64
 3   Number_of_Warts      89 non-null     float64
 4   Type                 85 non-null     float64
 5   Area                 90 non-null     int64  
 6   induration_diameter  88 non-null     float64
 7   Result_of_Treatment  90 non-null     int64  
dtypes: float64(4), int64(4)
memory usage: 5.8 KB


In [431]:
df.isnull().sum()

gender                 0
age                    0
Time                   3
Number_of_Warts        1
Type                   5
Area                   0
induration_diameter    2
Result_of_Treatment    0
dtype: int64

### Desc

1. Dataset ini sangat sedikit karena < 100 baris jadi diharapkan
   TIDAK MENGHAPUS baris data.
2. Target atribut dataset ini sangat imbalance jadi silakan menggunakan berbagai
   metode untuk menangani imbalance class
3. Untuk gender: 1 untuk male dan 2 untuk female
   Untuk results: 0 untuk tidak ada kemajuan dan 1 untuk ada kemajuan
4. Silakan membangun model Machine Learning dengan task baik 
   Classification, Regression, atau Clustering.
5. Silakan mengunggah notebook baik di e-learn maupun
   di Github (online text). Pastikan sudah urut code cell-nya dan harus
   sudah di- RUN ALL.

### Normalization #1

In [432]:
df = df.interpolate(method = 'pad')
df

gender  age   Time  Number_of_Warts  Type  Area  induration_diameter  \
0        1   15  11.00              6.0   1.0    30                 25.0   
1        1   27  11.75              6.0   1.0   208                  6.0   
2        1   32  12.00              9.0   1.0    43                 50.0   
3        1   33   1.75              7.0   2.0   379                  7.0   
4        1   34   5.00              7.0   3.0    64                  7.0   
..     ...  ...    ...              ...   ...   ...                  ...   
85       2   51   4.00              1.0   1.0    65                  7.0   
86       2   51   6.00              6.0   1.0    80                  2.0   
87       2   52   2.25              5.0   1.0    63                  7.0   
88       2   53  10.00              1.0   2.0    30                 25.0   
89       2   53   7.25              6.0   2.0    81                  7.0   

    Result_of_Treatment  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
..                  ...  
85                    1  
86                    1  
87                    1  
88                    1  
89                    1  

[90 rows x 8 columns]

In [433]:
df.isnull().sum()

gender                 0
age                    0
Time                   0
Number_of_Warts        0
Type                   0
Area                   0
induration_diameter    0
Result_of_Treatment    0
dtype: int64

In [434]:
df.duplicated().sum()

0

### Dealing with Imbalance Class

In [435]:
print(df['Result_of_Treatment'].value_counts())

1    71
0    19
Name: Result_of_Treatment, dtype: int64


In [436]:
#dependent variable and independent variable
X = df[['Result_of_Treatment']] == 0
y = df[['Result_of_Treatment']] == 1

In [437]:
#remapping
X = X.replace({True: 1, False: 0})
y = y.replace({True: 1, False: 0})

In [438]:
#reshaping
X_array = np.array(X)
X = X_array.reshape(1,-1)
y_array = np.array(y)
y = y_array.reshape(1,-1)

In [439]:
# SMOTE Oversampling
from imblearn.over_sampling import SMOTE
Count = Counter(y_train)
print(Count)
smt = SMOTE()
X_train_res, y_train_res = smt.fit_resample(X_train, y_train.values.ravel())
  
Counter2 = Counter(y_train_res)
print(Counter2)

Counter({True: 50, False: 13})


ValueError: Expected 2D array, got 1D array instead:
array=[False  True  True False False False False False False False False False
 False False False  True False False False False  True  True  True False
 False False False False False False False False False False  True False
 False False False False False False False False False  True False False
 False False False False  True  True False False False False  True False
  True False  True].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

### Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

log = LogisticRegression(random_state = 0)
log.fit(X_train, y_train.values.ravel())

ValueError: Expected 2D array, got 1D array instead:
array=[0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
y_pred = log.predict(X_test)
print(y_pred)

[ True  True  True  True  True  True  True  True  True]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

confusion = confusion_matrix(y_pred, y_test)
print(confusion)
print("Accuracy Score :")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))

[[0 0]
 [1 8]]
Accuracy Score :
0.8888888888888888
8


### KNN Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

log = KNeighborsClassifier(metric='euclidean')
log.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean')

In [ ]:
y_pred = log.predict(X_test)
print(y_pred)

[False  True  True  True  True  True  True  True  True]


In [ ]:
confusion = confusion_matrix(y_pred, y_test)
print(confusion)
print("Accuracy Score :")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))

[[0 1]
 [1 7]]
Accuracy Score :
0.7777777777777778
7


### Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

NB = GaussianNB()

In [ ]:
NB.fit(X_train,y_train)
print(y_train)

1     False
9     False
56     True
80     True
21     True
      ...  
46     True
34     True
62     True
26     True
32     True
Name: Result_of_Treatment, Length: 81, dtype: bool


In [ ]:
y_pred = NB.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix\n", cm)
print("Accuracy Score :")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))

Confusion Matrix
 [[0 1]
 [0 8]]
Accuracy Score :
0.8888888888888888
8
